---
upload_path: "/upload-folder"
frontmatter_file_url_template: "/front-matter-2"
body_file_url_template: "/body-2"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
collections: ''
